### ISSUE TITLE
how to run the demo correctly

### ISSUE THREAD

**Issue by king-zark** [cs-chan/Exclusively-Dark-Image-Dataset#13]
thank you for the repository very much, when I try to run the demo, it says '未定义与 'function_handle' 类型的输入参数相对应的函数 'minimize'' in function gen-en(), and I can't find where is wrong, hope your help!

**Comment by yploh** [comment]
Hi, 
I believe you have not installed the toolboxes correctly.
For this particular error, it is related to the GPR_v1.1.zip.
You must unzip the GPR_v1.1.zip file, and included the folder and all its subfolders as part of your MATLAB directory.
