### ISSUE TITLE
ExDark in VOC format

### ISSUE THREAD

**Issue by surajpaib** [cs-chan/Exclusively-Dark-Image-Dataset#14]
Hi authors!
Thank you for this amazing dataset. I've been using it for a low-light enhancement project for one of my masters courses. 

To compare with VOC dataset, I have converted the ExDark dataset into PASCAL VOC format and tested it with a VOC annotation viewer to confirm. 

If you would like me to share this formatted version of the dataset which can allow super easy comparisons between PASCAL VOC and ExDark, I would be happy to do so.

**Comment by WZHsmile** [comment]
> Hi authors!
> Thank you for this amazing dataset. I've been using it for a low-light enhancement project for one of my masters courses.
> 
> To compare with VOC dataset, I have converted the ExDark dataset into PASCAL VOC format and tested it with a VOC annotation viewer to confirm.
> 
> If you would like me to share this formatted version of the dataset which can allow super easy comparisons between PASCAL VOC and ExDark, I would be happy to do so.

Hello, I am very interested in your work, ExDark in VOC format. Would you please share with me the Annotations of this VOC format?  ( my Email :  wzh1205@outlook.com )

**Comment by surajpaib** [comment]
@WZHsmile Sure! I will upload it to a drive over the weekend and share the link

**Comment by surajpaib** [comment]
@WZHsmile  Here is the link to the zip file: https://drive.google.com/open?id=151j-h_abejzPNglEt3ml-kNrnYvgbm2F

**Comment by WZHsmile** [comment]
@surajpaib  Thank you very much for sharing!

**Comment by Egolee0713** [comment]
@surajpaib  @WZHsmile  hi, https://drive.google.com/open?id=151j-h_abejzPNglEt3ml-kNrnYvgbm2F this link is not work,  it would be nice if  you can  provide the other link to download?

**Comment by yaz94** [comment]
@surajpaib 

Kindly, can you provide another link, since the one shared is not working!!

Thanks in advance,
