### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by OlafenwaMoses** [cs-chan/Exclusively-Dark-Image-Dataset#18]
The link to download the dataset no longer works. Can you provide a Google Drive link instead?

**Comment by muku314115** [comment]
Use inspect element and access the link

**Comment by OlafenwaMoses** [comment]
Thanks @MukundIsGod . I was able to download it via a version uploaded to Kaggle. The link is below.

https://www.kaggle.com/mangosata/exclusivelydarkimagedataset-from-cschan
