### ISSUE TITLE
Question about the LICENSE

### ISSUE THREAD

**Issue by Ir1d** [cs-chan/Exclusively-Dark-Image-Dataset#2]
Hi thx for your work!
I'm writing to ask the LICENSE for the dataset.
I noticed "BSD-3" in https://github.com/cs-chan/Exclusively-Dark-Image-Dataset#license-and-copyright while in https://github.com/cs-chan/Exclusively-Dark-Image-Dataset/blob/master/LICENSE it shows GPL.
Thx in advance.

**Comment by cs-chan** [comment]
Thank you very much. We have updated the LICENSE. It is under BSD-3.
