### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by ShenZheng2000** [cs-chan/Exclusively-Dark-Image-Dataset#22]
The exclusively dark image cannot be downloaded from the given [URL](https://drive.google.com/file/d/1GZqHFzTLDI-1rcOctHdf-c16VgagWocd/view?usp=sharing)

![image](https://user-images.githubusercontent.com/69662345/179440690-2d89cb4f-a840-42ad-acc3-206dfed503ee.png)

I hope you can provide a new valid link. Thank you!

**Comment by xiaobiaodu** [comment]
Hi. I meet the same problem. Did you fix it?

**Comment by bekir23** [comment]
I also have this problem. I searched this dataset on internet to find another source. You can reach it by https://www.kaggle.com/datasets/mangosata/exclusivelydarkimagedataset-from-cschan

**Comment by ShenZheng2000** [comment]
@bekir23 Thanks very much for your link.
