### ISSUE TITLE
SPIC data

### ISSUE THREAD

**Issue by a462428** [cs-chan/Exclusively-Dark-Image-Dataset#3]
Hi, really thx for your useful data!
Besides, I thought SPIC is good. Is it convenient to offer data after using “SPIC” cuz I don’t have matlab Q_Q. Thx!

**Comment by cs-chan** [comment]
Hi, thx for interest. May I know what to you mean by “offer data after using SPIC”?

**Comment by loqoella** [comment]
Are the data in ExDark raw data?

**Comment by yploh** [comment]
> Are the data in ExDark raw data?

Duplicate of #10
