### ISSUE TITLE
Annotation Problem

### ISSUE THREAD

**Issue by supercaoO** [cs-chan/Exclusively-Dark-Image-Dataset#4]
Hello, thanks to your contribution.
I have some confusion about the annotation generation.
You mentioned that "The annotations are generated using Piotr's Computer Vision Matlab Toolbox (PMT)"  in the README of Groundtruth.
Since I haven't used PMT before, I want to find out the meaning of this sentence.

I want to confirm whether the annotations are labeled manually by you or auto-detected by algorithms from PMT.

**Comment by yploh** [comment]
> Hello, thanks to your contribution.
> I have some confusion about the annotation generation.
> You mentioned that "The annotations are generated using Piotr's Computer Vision Matlab Toolbox (PMT)" in the README of Groundtruth.
> Since I haven't used PMT before, I want to find out the meaning of this sentence.
> 
> I want to confirm whether the annotations are labeled manually by you or auto-detected by algorithms from PMT.

All the annotations are done manually.

**Comment by shraddhagugulothu** [comment]
Sir annotations are given in .txt format. How to convert it into coco annotation format. I have tried many ways still getting errors
