### ISSUE TITLE
Annotations Indexing

### ISSUE THREAD

**Issue by adityac8** [cs-chan/Exclusively-Dark-Image-Dataset#5]
Hi,
Thank you for such an amazing dataset.
I read that the annotation format is as follows:

> Bounding box coordinates [l t w h]

I wanted to know whether the annotations for the images are 1-indexed (like Pascal VOC) or 0-indexed (like MS COCO).

Thanks

**Comment by yploh** [comment]
> Hi,
> Thank you for such an amazing dataset.
> I read that the annotation format is as follows:
> 
> > Bounding box coordinates [l t w h]
> 
> I wanted to know whether the annotations for the images are 1-indexed (like Pascal VOC) or 0-indexed (like MS COCO).
> 
> Thanks

The annotations are 1-indexed like Pascal VOC
