### ISSUE TITLE
how to run demo successfully

### ISSUE THREAD

**Issue by wangyx-chn** [cs-chan/Exclusively-Dark-Image-Dataset#6]
thank you for the repository very much, when I try to run the demo , it said "尝试将 SCRIPT vl_nnconv 作为函数执行:", I want to know  what I should do before running the demo? thank you again!

**Comment by yploh** [comment]
Hi,
I believe you did not setup your matconvnet toolbox correctly, so the path is pointing to the instruction script vl_nnconv instead of the function script with the same name.
I suggest you run vl_setupnn first, so that the path can be corrected, and then try again.
