### ISSUE TITLE
Subset from MS-COCO

### ISSUE THREAD

**Issue by ObeliskChoi** [cs-chan/Exclusively-Dark-Image-Dataset#9]
Thank you for this awesome work! 
I would like to do some study based on your paper and novel ExDARK dataset. Could you provide the image list of the MS-COCO subset and its division of train/val/test sets in your paper "Getting to know low-light images with the Exclusively Dark dataset"?
Thx!

**Comment by cs-chan** [comment]
Apologies for the late reply.

Thank you for the interest in our work.

Please find the requested information (image list, labels, and sets) in the attached .txt file. The numbering is the same as the ExDARK annotation.

Thank you. 

Regards,
LOH Yuen Peng
[cocoset.txt](https://github.com/cs-chan/Exclusively-Dark-Image-Dataset/files/4142298/cocoset.txt)
